name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install and build
        run: |
          npm install
          gatsby build --prefix-paths
      - name: push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
